services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000

    depends_on:
      - db
    networks:
      - app_network  # Conecta à rede personalizada

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-bookstore}
    networks:
      - app_network  # Conecta à rede personalizada

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
