# Generated by Django 5.1.2 on 2024-11-28 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='data_criacao',
        ),
    ]
