name: CI for Bookstore Project

on:
  push:
    branches:
      - main  # Aciona o fluxo de trabalho em qualquer push para a branch main
  pull_request:
    branches:
      - main  # Aciona o fluxo de trabalho quando um pull request é feito para a branch main

jobs:
  test:
    runs-on: ubuntu-latest  # O fluxo de trabalho será executado em uma máquina virtual Ubuntu mais recente

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Action que faz o checkout do código do repositório

      - name: Set up Python
        uses: actions/setup-python@v4  # Action para configurar o Python
        with:
          python-version: '3.9'  # Define a versão do Python para a execução

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Atualiza o pip
          pip install -r requirements.txt  # Instala as dependências listadas no arquivo requirements.txt

      - name: Run tests
        run: |
          pytest  # Executa os testes automatizados com pytest (se você estiver usando pytest)
